### ISSUE TITLE
plugins para Bagisto

### ISSUE THREAD

**Issue by marcelowu** [mateusjunges/laravel-pix#1]
possivel ou pretende fazer um plugins para Bagisto ? A Free and Opensource Laravel eCommerce.
https://github.com/bagisto/bagisto
https://devdocs.bagisto.com/1.x/advanced/create_payment_method.html#_1-by-using-bagisto-package-generator

**Comment by mateusjunges** [comment]
Olá @marcelowu, no momento não estou com tempo para desenvolver um plugin, mas caso você deseje pode utilizar o pacote para implementar sua solução. Abraço!
