### ISSUE TITLE
Compatibilidade v5.x

### ISSUE THREAD

**Issue by maikealame** [mateusjunges/laravel-pix#12]
Buenas, obrigado pelo belo trabalho !

Existe pretensão de suporte para as versões anteriores do Laravel ?
Rodei em uma aplicação 5.8 e passei pelo seguinte problema:

```
>>> $api = Pix::api()->clientId('client_id')->clientSecret('client_secret');
=> Junges\Pix\Api\Api {#3591}
>>> $token = Pix::api()->getOauth2Token()->json();
PHP Error:  Class 'Illuminate/Support/Facades/Http' not found in /var/www/fotografoem/vendor/mateusjunges/laravel-pix/src/Api/Auth.php on line 33
```

Essa classe só existe a partir de v7, segue link da última release da v6 que não possui ainda:
https://github.com/laravel/framework/tree/v6.20.37/src/Illuminate/Support/Facades

**Comment by mateusjunges** [comment]
Olá, desculpe, mas não tenho planos para suportar versões antes da 7.x do laravel. Você pode tentar dar upgrade na versão da framework na sua aplicação usando [este guia](https://laravel.com/docs/7.x/upgrade), ou, dar fork neste projeto e trocar as requests que utilizam o Http para requests via guzzle.
