### ISSUE TITLE
Ajuda.

### ISSUE THREAD

**Issue by ghost** [mateusjunges/laravel-pix#9]
Cara Boa tarde, sou programador SourcePawn, não intendo nada de PHP ou Laravel ,teria como integrar esse sistema pix como forma de pagamento em https://github.com/Azuriom/Plugin-Shop ? já tem outras formas de pagamento porem nenhuma maleável como pix , teria que ter um aguarde na compra ate a confirmação que o pix foi realizado .

**Comment by mateusjunges** [comment]
Olá @Stewart-Anubis, este pacote fornece um meio mais fácil de integrar um PSP (Provedor de serviços de pagamento) ao seu site, contanto que o PSP siga as convençoes estabelecidas pelo BACEN quanto a API pix. Estou implementando uma feature para tornar os endpoints configuráveis, pois já percebi que vários PSPs não seguem esta convenção. Você pode integrar o PIX utilizando este pacote no seu projeto, mas precisa das credencias do provedor pix para conseguir utilizar a aplicação para gerar e consultar qr codes. Espero ter ajudado, qualquer coisa fique a vontade para reabrir esta issue.
